amozilla/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using amozilla.Models;
namespace amozilla.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket cart;
        public CartSummaryViewComponent(Basket basketService)
        {
            cart = basketService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
    
}

amozilla/Components/TypesViewComponent.cs
using System;
using System.Linq;
using amozilla.Models;
using Microsoft.AspNetCore.Mvc;

namespace amozilla.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookRepository repo { get; set; }
        public TypesViewComponent (IBookRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["bookGenre"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }

    }
}

amozilla/Views/Shared/BookSummary.cshtml
@{
}
@model Book
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <h4>@Model.Title</h4>
        <span class="badge bg-info" style="float:right">
            Genre: @Model.Category
        </span>
    </div>

    <ul>
        <li>Author: @Model.Author</li>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.Isbn</li>

        <li>Number of Pages: @Model.PageCount</li>
        <li>Price: @Model.Price</li>
    </ul>

    <form method="post" asp-page="/Cart">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm" style="float:right">Add to Cart</button>
        </span>

    </form>

</div>

amozilla/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - amozilla</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white " asp-area="" asp-controller="Home" asp-action="Index">amozilla</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="bg-dark text-white p-2">
                    <div class="container-fluid">
                        <div class="row">
                            
                            <div class="col-6 text-right">
                                <vc:cart-summary />
                            </div>
                        </div>
                    </div>
                </div>
                @*<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
            </ul>
        </div>*@
            </div>
        </nav>
    </header>
    <div class="row m-1 p-1">
        <div id="types" class=" = col-3">
            <vc:types></vc:types>
        </div>
        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="margin:auto">
            &copy; 2022 - amozilla - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>