amozilla/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using amozilla.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace amozilla.Controllers
{
    public class PurchaseController : Controller
    {
        private IPurchaseRepository repo { get; set; }
        private Basket basket;
        public PurchaseController (IPurchaseRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty!");
            }

            if (ModelState.IsValid)
            {
                purchase.Lines = basket.Items.ToArray();
                repo.SavePurchase(purchase);
                basket.ClearBasket();

                return RedirectToPage("/PurchaseConfirmation");

            }
            else
            {
                return View();
            }
        }
    }
}

amozilla/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using amozilla.Infrastructure;
using amozilla.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace amozilla.Pages
{
    public class CartModel : PageModel
    {
        private IBookRepository repo { get; set; }

        public Basket basket { get; set; }

        public string ReturnUrl { get; set; }

        public CartModel(IBookRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);


            basket.AddItem(b, 1);


            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Book.BookId == bookId).Book);
            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

amozilla/Pages/PurchaseConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace amozilla.Pages
{
    public class PurchaseConfirmationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

amozilla/Pages/Cart.cshtml
@page
@model amozilla.Pages.CartModel




<h2>Your Cart</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>


    <tbody>
        @foreach(var i in Model.basket.Items)
        {
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>@i.Book.Price</td>
                <td>$@((i.Quantity * i.Book.Price).ToString("#,##0.00"))</td>

                <td class=text-center>
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="bookId" value="@i.Book.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">Total</td>
            <td>$@Model.basket.CalculateTotal().ToString("#,##0.00")</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Back to Shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Purchase">Checkout</a>
</div>

amozilla/Pages/PurchaseConfirmation.cshtml
@page
@model amozilla.Pages.PurchaseConfirmationModel
@{
}
<div class="text-center">
    <h2>Thank you for your order!</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

amozilla/Pages/_CartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white " asp-area="" asp-controller="Home" asp-action="Index">amozilla</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>

    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>